from __future__ import annotations

from .audit import AuditReport
from .crawlers import AI_CRAWLERS


def generate_robots_patch(existing_robots_text: str, report: AuditReport) -> str:
    """Return a full replacement robots.txt: keeps every line the site already
    had, and appends an explicit Allow-all group for each blocked AI crawler.
    Non-destructive by construction — nothing existing is deleted or edited.
    """
    if not report.blocked_agents:
        return existing_robots_text

    lines = existing_robots_text.rstrip("\n").splitlines() if existing_robots_text.strip() else []
    lines.append("")
    lines.append("# --- Added by aivisible-fix: explicitly allow AI crawlers ---")
    lines.append("# Remove any of these blocks if you deliberately don't want that")
    lines.append("# crawler training on / citing your content.")
    for agent in report.blocked_agents:
        lines.append("")
        lines.append(f"User-agent: {agent}")
        lines.append("Allow: /")
    return "\n".join(lines) + "\n"


def generate_llms_txt(site_name: str, site_description: str, key_pages: list[tuple[str, str]]) -> str:
    """key_pages: list of (title, url) tuples for the handful of pages worth
    pointing an LLM at directly (docs, pricing, about) — per the llms.txt spec
    (llmstxt.org): an H1, a one-line summary, then link sections.
    """
    lines = [f"# {site_name}", "", f"> {site_description}", ""]
    if key_pages:
        lines.append("## Key pages")
        for title, url in key_pages:
            lines.append(f"- [{title}]({url})")
        lines.append("")
    lines.append(
        "<!-- Generated by aivisible-fix. Edit freely — this is a starting point, "
        "not a final file. Keep it short: link out rather than duplicating content. -->"
    )
    return "\n".join(lines) + "\n"


def suggest_jsonld_snippet(site_name: str, site_url: str, description: str) -> str:
    return f"""<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "{site_name}",
  "url": "{site_url}",
  "description": "{description}"
}}
</script>"""


def summarize_unknown_crawler_coverage() -> str:
    return (
        f"This tool checks {len(AI_CRAWLERS)} known AI crawler user-agents. "
        "New ones ship periodically — re-run the audit monthly rather than treating "
        "a clean report as permanent."
    )
